sudo: required
language: go
go:
  - 1.6
services:
  - docker

before_install:
  - docker pull resin/raspberrypi3-golang
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - sh build.sh

after_success:
  - sh deploy.sh
