sudo: required
language: go
go:
  - 1.6
services:
  - docker

before_install:
  - docker pull resin/raspberrypi3-golang
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - docker build -t "$DOCKER_USERNAME"/getip src/getip

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push "$DOCKER_USERNAME"/getip

