apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  labels:
    app: debug
spec:
  containers:
  - name: debug
    image: arm32v7/busybox
    command: ['sh', '-c', 'while true; do sleep 3600; done']
