apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: getip-deployment
  labels:
    app: getip
spec:
  replicas: 4
  selector:
    matchLabels:
      app: getip
  template:
    metadata:
      labels:
        app: getip
    spec:
      containers:
      - name: getip
        image: 192.168.178.80:5000/getip:v1
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: getip
spec:
  externalIPs:
  - 192.168.178.80
  selector:
    app: getip
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
